import { Review } from '../types';

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-001',
    name: 'Sarah Lin',
    email: 'sarah.lin@finscale.io',
    role: 'Head of Product',
    company: 'FinScale',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'Cut our sales cycle in half with social proof',
    content: 'Embedding testimonials directly on our checkout page increased our conversion rate by 34% in the very first month. The widgets look native and match our brand aesthetic flawlessly.',
    type: 'text',
    tags: ['Conversion', 'SaaS', 'High ROI'],
    source: 'form',
    status: 'approved',
    isFeatured: true,
    consent: true,
    helpfulCount: 42,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: 'rev-002',
    name: 'Marcus Thorne',
    email: 'marcus@hyperstack.io',
    role: 'Founder & CTO',
    company: 'HyperStack',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'The cleanest developer experience by far',
    content: 'We migrated from Senja and the difference in load speed and clean developer ergonomics is night and day. Having direct control over our database while using these pre-built UI components is unmatched.',
    type: 'text',
    tags: ['Developer Experience', 'Performance', 'Migration'],
    source: 'form',
    status: 'approved',
    isFeatured: true,
    consent: true,
    helpfulCount: 28,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: 'rev-003',
    name: 'Elena Rostova',
    email: 'elena@novadesign.co',
    role: 'Lead UX Designer',
    company: 'Nova Design Studio',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'Our clients are obsessed with the Wall of Love',
    content: 'The typography, glassmorphic cards, and subtle animations make our client wall look like a high-end luxury brand. Submitting a review takes 30 seconds and our clients actually enjoy it.',
    type: 'text',
    tags: ['UI/UX', 'Design', 'Client Feedback'],
    source: 'form',
    status: 'approved',
    isFeatured: true,
    consent: true,
    helpfulCount: 19,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: 'rev-004',
    name: 'Devon Vance',
    email: 'devon@orbitflow.net',
    role: 'Growth Marketing Lead',
    company: 'OrbitFlow',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    rating: 4,
    title: 'Super easy to integrate with Netlify & Firebase',
    content: 'We plugged it into our Firebase instance in under 10 minutes and deployed straight to Netlify. Testimonials populate instantly and the dashboard gives our marketing team full moderation control.',
    type: 'text',
    tags: ['Integration', 'Firebase', 'Netlify'],
    source: 'form',
    status: 'pending',
    isFeatured: false,
    consent: true,
    helpfulCount: 6,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
  {
    id: 'rev-005',
    name: 'Aisha Patel',
    email: 'aisha@zenithapp.org',
    role: 'VP of Engineering',
    company: 'Zenith Health',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'Finally an open architecture with zero lock-in',
    content: 'We needed full HIPAA compliance and own-database storage. The pluggable architecture allowed us to connect our self-hosted PostgreSQL without being locked into proprietary SaaS vendors.',
    type: 'text',
    tags: ['Security', 'Self-Hosted', 'Open Source'],
    source: 'form',
    status: 'pending',
    isFeatured: false,
    consent: true,
    helpfulCount: 12,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'rev-006',
    name: 'Alex Rivera',
    email: 'alex@codepath.dev',
    role: 'Full Stack Engineer',
    company: 'CodePath',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    rating: 4,
    title: 'Love the video testimonial option',
    content: 'Being able to collect Loom and video URLs alongside written testimonials gave us authentic video snippets for our landing page hero section.',
    type: 'video',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    tags: ['Video', 'Authenticity'],
    source: 'form',
    status: 'approved',
    isFeatured: false,
    consent: true,
    helpfulCount: 8,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
  }
];
