import React, { useState } from 'react';
import { Sparkles, Heart, AlertCircle, MessageCircle, TrendingUp, ChevronRight } from 'lucide-react';

export const AnalyzeView: React.FC = () => {
  const [activeAnalysis, setActiveAnalysis] = useState<string>('loved');

  const options = [
    {
      id: 'loved',
      title: 'What your customers love about you',
      icon: Heart,
      color: 'text-rose-500',
      bg: 'bg-rose-50',
      summary: 'High satisfaction in ease of use (94%), immediate customer support turnaround, and automated workflows.',
      bullets: [
        '94% mention quick setup taking under 3 minutes.',
        'Customers frequently praise fast support response times.',
        'High willingness to recommend to peer networks.',
      ],
    },
    {
      id: 'pain-points',
      title: 'Custom pain points',
      icon: AlertCircle,
      color: 'text-amber-500',
      bg: 'bg-amber-50',
      summary: 'Identified friction points in onboarding and third-party CSV column mapping.',
      bullets: [
        'Non-technical users requested single-click OAuth imports over CSV files.',
        'A few customers noted video upload limits on slower networks.',
      ],
    },
    {
      id: 'phrases',
      title: 'Common phrases',
      icon: MessageCircle,
      color: 'text-blue-500',
      bg: 'bg-blue-50',
      summary: 'Frequently occurring sentiment keywords across approved proof.',
      bullets: [
        '"Game changer for social proof"',
        '"Took less than 3 minutes to collect"',
        '"Boosted my conversion rate immediately"',
      ],
    },
    {
      id: 'improvements',
      title: 'What can be improved',
      icon: TrendingUp,
      color: 'text-emerald-500',
      bg: 'bg-emerald-50',
      summary: 'Actionable suggestions generated by AI from collected feedback.',
      bullets: [
        'Add Slack notifications whenever a 5-star review is captured.',
        'Provide automated Twitter / LinkedIn share reminders after approving a review.',
      ],
    },
  ];

  const current = options.find(o => o.id === activeAnalysis) || options[0];

  return (
    <div className="max-w-6xl mx-auto py-8 px-4 sm:px-6 space-y-6 font-sans">
      
      {/* Header (Matches Senja 03:59) */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-gray-100">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 tracking-tight font-display">Analysis</h1>
          <p className="text-xs text-gray-500 mt-1">
            AI-powered intelligence and sentiment extraction from your customer proof.
          </p>
        </div>

        <button className="px-4 py-2 rounded-xl bg-purple-50 hover:bg-purple-100 text-[#6701e6] border border-purple-200 text-xs font-bold transition-all shadow-2xs flex items-center gap-1.5 self-start sm:self-auto cursor-pointer">
          <Sparkles className="w-3.5 h-3.5" />
          <span>Select Testimonials</span>
        </button>
      </div>

      {/* 2-Column Layout (Matches Senja 03:59) */}
      <div className="grid grid-cols-1 md:grid-cols-12 gap-6 items-start">
        
        {/* Left Options List */}
        <div className="md:col-span-5 space-y-3">
          {options.map((opt) => {
            const Icon = opt.icon;
            const isSelected = activeAnalysis === opt.id;
            return (
              <button
                key={opt.id}
                onClick={() => setActiveAnalysis(opt.id)}
                className={`w-full p-4 rounded-2xl border text-left transition-all flex items-center justify-between gap-3 cursor-pointer ${
                  isSelected
                    ? 'bg-purple-50/60 border-[#6701e6] shadow-xs'
                    : 'bg-white border-gray-200 hover:border-gray-300 hover:bg-gray-50/50'
                }`}
              >
                <div className="flex items-center gap-3">
                  <div className={`w-8 h-8 rounded-xl ${opt.bg} ${opt.color} flex items-center justify-center shrink-0`}>
                    <Icon className="w-4 h-4" />
                  </div>
                  <span className="text-xs font-bold text-gray-900">{opt.title}</span>
                </div>
                <ChevronRight className={`w-4 h-4 ${isSelected ? 'text-[#6701e6]' : 'text-gray-300'}`} />
              </button>
            );
          })}
        </div>

        {/* Right Output Panel */}
        <div className="md:col-span-7 bg-white border border-gray-200 rounded-3xl p-6 sm:p-8 shadow-xs space-y-4">
          <div className="flex items-center gap-2 text-xs font-bold text-[#6701e6]">
            <Sparkles className="w-4 h-4" />
            <span>AI Customer Intelligence</span>
          </div>

          <h3 className="text-lg font-bold text-gray-900 font-display">
            {current.title}
          </h3>

          <p className="text-xs text-gray-600 leading-relaxed bg-gray-50 p-3.5 rounded-xl border border-gray-100">
            {current.summary}
          </p>

          <div className="space-y-2 pt-2">
            <span className="text-xs font-bold text-gray-800">Key Takeaways</span>
            <ul className="space-y-2">
              {current.bullets.map((b, i) => (
                <li key={i} className="text-xs text-gray-600 flex items-start gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-[#6701e6] mt-1.5 shrink-0" />
                  <span>{b}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

      </div>

    </div>
  );
};
